In [1]:
import numpy as np
import pandas as pd
import glob
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from os import listdir
from os.path import isfile, join
from PIL import Image
from sklearn.preprocessing import StandardScaler
import matplotlib.colors as mcolors

In [2]:
#Reading data
print("Reading data...")
data_filenames = []
for root, dirs, files in os.walk('data/raw_images/'):  
    for filename in files:
        data_filenames.append('data/raw_images/'+filename)

data = [np.array(Image.open(filename)) for filename in data_filenames[:10]]
print("Number of raw images: \t", end="")
print(len(data))

print("\nReading annotated images of segmentation...")
annot_filenames = []
for root, dirs, files in os.walk('data/class_color/'):  
    for filename in files:
        annot_filenames.append(filename)
    
annot = [np.array(Image.open('data/class_color/' + filename).convert('RGB')) for filename in annot_filenames[:10]]
print("Number of annotated images: \t", end="")
print(len(annot))
if len(data)==len(annot):
    print("\nAll raw images are annotated.\n")


Reading data...
Number of raw images: 	10

Reading annotated images of segmentation...
Number of annotated images: 	10

All raw images are annotated.



In [3]:
#Reading .csv file containing metadata about the segmentation
print("Reading file containing metadata about the segmentation...")
metadf = pd.read_csv('data/categories.csv', sep=',')

#Organizing subcategories into an array, and counting subcategories
subcat = []
no_subcat = 0
for row in metadf.name:
    subcat.append(row)
no_subcat = len(subcat)

#Organizing categories into an array
cat = []
for row in metadf.category:
    cat.append(row)

#Organizing category Ids into an array
catid = []
for row in metadf.catId:
    catid.append(row)
#Counting categories
no_cat = 1
act = catid[0]
categories = [] #array containing categories without duplication
categories.append(cat[0])
for i in range(len(catid)):
    if catid[i]!=act:
        categories.append(cat[i])
        no_cat+=1
        act=catid[i]

#Organizing subcategory RGB colors into an array
col = []
for row in metadf.color:
    c = row.replace(" ", "").split(',')
    rgb = []
    for i in c:
        rgb.append(int(i))
    col.append(rgb)


print('Number of segmentation subcategories:', no_subcat)
print('Number of segmentation categories:', no_cat, "\n")
print("Subcategories and their representational colors [R, G, B]: \n")
for i in range(len(subcat)):
    print("%30s \t" % subcat[i], end ="")
    print(i, "  ", col[i])


Reading file containing metadata about the segmentation...
Number of segmentation subcategories: 41
Number of segmentation categories: 8 

Subcategories and their representational colors [R, G, B]: 

                     unlabeled 	0    [0, 0, 0]
                       dynamic 	1    [111, 74, 0]
                   ego vehicle 	2    [0, 0, 0]
                        ground 	3    [81, 0, 81]
                        static 	4    [0, 0, 0]
                       parking 	5    [250, 170, 160]
                    rail track 	6    [230, 150, 140]
                          road 	7    [128, 64, 128]
                      sidewalk 	8    [244, 35, 232]
                        bridge 	9    [150, 100, 100]
                      building 	10    [70, 70, 70]
                         fence 	11    [190, 153, 153]
                        garage 	12    [180, 100, 180]
                    guard rail 	13    [180, 165, 180]
                        tunnel 	14    [150, 120, 90]
                         wall  

In [4]:
# catid_annot_filenames = []
# for root, dirs, files in os.walk('test_data/catid_annot/'):  
#     for filename in files:
#         catid_annot_filenames.append('test_data/catid_annot/'+filename)

# catid_annot = []
# if len(catid_annot_filenames) == len(annot):
#     print('Catid Files Already Exist')
#      for img in range(len(annot)):
#         catid_annot_img = np.fromfile('data/catid_annot/'+str(img) +'.txt', dtype=int)
#         catid_annot.append(catid_annot_img)
        
# if len(catid_annot_filenames) != len(annot):
#     print('Catid Files DO NOT Exist')
#     for img in range(len(annot)):
#         catid_annot_img = []
#         for index, row in enumerate(annot[img]):
#             blabla = []
#             for j, pixel in enumerate(row):
#                 blabla.append(col.index(list(row[j])))
#             catid_annot_img.append(blabla)
#         np.array(catid_annot_img).tofile('data/catid_annot/' +str(img) +'.txt')
#         catid_annot.append(catid_annot_img)
#         catid_annot_filenames = []
#         for root, dirs, files in os.walk('data/catid_annot/'):  
#             for filename in files:
#                 catid_annot_filenames.append('data/catid_annot/'+filename)
        
# if len(catid_annot) == len(annot):
#      print('Reading in subcategory id annotated matrices: successful')
# else :
#      print('Reading in subcategory id annotated matrices: UNSUCCESSFUL')

In [5]:
img = annot[0]
catid_annot_img = []
for index, row in enumerate(img):
    catid_row = []
    for j, pixel in enumerate(row):
        catid_row.append(col.index(list(row[j])))
        if j%40 == 0:
            print(pixel)
            print(row[j])
            print(col.index(list(row[j])))
    catid_annot_img.append(catid_row)

if len(catid_annot_img) == len (annot):
    print('Reading in subcategory id annotated matrices: successful')
else :
    print('Reading in subcategory id annotated matrices: UNSUCCESSFUL')

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[153 153 153]
[153 153 153]
20
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130

30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 

30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 

27
[250 170 250]
[250 170 250]
27
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 

29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[153 153 153]
[153 153 153]
20
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 

30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[153 153 153]
[153 153 153]
20
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[250 170 250]
[250 170 250]
27
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 

30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 0  0 70]
[ 0  0 70]
40
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 18

30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 0  0 70]
[ 0  0 70]
40
[ 0  0 70]
[ 0  0 70]
40
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 7

30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 0  0 70]
[ 0  0 70]
40
[ 0  0 70]
[ 0  0 70]
40
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 7

29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 0  0 70]
[ 0  0 70]
40
[ 0  0 70]
[ 0  0 70]
40
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[10

30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 0  0 70]
[ 0  0 70]
40
[ 0  0 70]
[ 0  0 70]
40
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 7

29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[150 100 100]
[150 100 100]
9
[107 142  35]
[107 142  35]
29
[150 100 100]
[150 100 100]
9
[150 100 100]
[150 100 100]
9
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 0  0 70]
[ 0  0 70]
40
[ 0  0 70]
[ 0  0 70]
40
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 1

29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[128  64 128]
[128  64 128]
7
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 0  0 70]
[ 0  0 70]
40
[ 0  0 70]
[ 0  0 70]
40
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[ 70 130 180]
[ 70 130 180]
30
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[  0   0 142]
[  0   0 142]
35
[152 251 152]
[152 251 152]
28
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107

29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[152 251 152]
[152 251 152]
28
[152 251 152]
[152 251 152]
28
[152 251 152]
[152 251 152]
28
[152 251 152]
[152 251 152]
28
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[  0   0 142]
[  0   0 142]
35
[152 251 152]
[152 251 152]
28
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[180 165 180]
[180 165 180]
13
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[128  64 128]
[128  64 128]
7
[107 142  35]
[107 142  35]
29
[ 0  0 70]
[ 0  0 70]
40
[ 0  0 70]
[ 0  0 70]
40
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[ 0  0 70]
[ 0  0 70]
40
[128  64 128]
[128  64 128]
7
[152 251 152]
[152 251 152]
28
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[107 142  35]
[107 142  35]
29
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 12

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[152 251 152]
[152 251 152]
28
[107 142  35]
[107 142  35]
29
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[128  64 128]
[128  64 128]
7
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  

35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[152 251 152]
[152 251 152]
28
[152 251 152]
[152 251 152]
28
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]


7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[  0   0 142]
[  0   0 142]
35
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[  0   0 142]
[  0   0 142]
35
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[180 165 180]
[180 165 180]
13
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[180 165 180]
[180 165 180]
13
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  6

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 1

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 1

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 1

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 1

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64

[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 1

[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 1

7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64 128]
[128  64 128]
7
[128  64